---
- name: Deploy url_shortener container
  hosts: all
  become: true
  vars:
    container_name: url_shortener

  tasks:
    - name: Pull image from Nexus registry
      community.docker.docker_image:
        name: "{{ image_tag }}"
        source: pull

    - name: Stop existing container (if any)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_tag }}"
        state: started
        restart_policy: always
        networks:
          - name: devops-net
        ports:
          - "8000:8000"
        env:
          ENVIRONMENT: "{{ env }}"
          KAFKA1: "localhost"
          KAFKA2: "localhost"
          KAFKA3: "localhost"
          KAFKA_PORT: "9092"
          ROCKSDB_SHARD1: "localhost"
          ROCKSDB_SHARD2: "localhost"
          ROCKSDB_SHARD3: "localhost"
          ROCKSDB_BACKUP1: "localhost"
          REDIS_HOST: "redis"
          REDIS_PORT: "6379"
          REDIS_PASS: ""
          DOCKER_IP: "localhost"
          DOCKER_PORT: "8000"
          ODP_IP: "localhost"
          ODP_PORT: "8080"