%% -*- coding: utf-8 -*-
%% @private
%% Automatically @generated, do not edit
%% Generated by gpb_compile version 4.21.5
%% Version source: file
-module(route_guide_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types

-export_type([]).

%% message types
-type key() ::
      #{channel                 => unicode:chardata(), % = 1, optional
        identifier              => unicode:chardata(), % = 2, optional
        msg_uuid                => unicode:chardata() % = 3, optional
       }.

-type value() ::
      #{json_payload            => unicode:chardata(), % = 1, optional
        stored_at               => integer()        % = 2, optional, 64 bits
       }.

-type put_request() ::
      #{key                     => key(),           % = 1, optional
        value                   => value(),         % = 2, optional
        if_absent               => boolean() | 0 | 1 % = 3, optional
       }.

-type put_response() ::
      #{created                 => boolean() | 0 | 1, % = 1, optional
        value                   => value()          % = 2, optional
       }.

-type get_request() ::
      #{key                     => key()            % = 1, optional
       }.

-type get_response() ::
      #{value                   => value()          % = 1, optional
       }.

-type delete_request() ::
      #{key                     => key()            % = 1, optional
       }.

-type delete_response() ::
      #{deleted                 => boolean() | 0 | 1 % = 1, optional
       }.

-export_type(['key'/0, 'value'/0, 'put_request'/0, 'put_response'/0, 'get_request'/0, 'get_response'/0, 'delete_request'/0, 'delete_response'/0]).
-type '$msg_name'() :: key | value | put_request | put_response | get_request | get_response | delete_request | delete_response.
-type '$msg'() :: key() | value() | put_request() | put_response() | get_request() | get_response() | delete_request() | delete_response().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        key -> encode_msg_key(id(Msg, TrUserData), TrUserData);
        value -> encode_msg_value(id(Msg, TrUserData), TrUserData);
        put_request -> encode_msg_put_request(id(Msg, TrUserData), TrUserData);
        put_response -> encode_msg_put_response(id(Msg, TrUserData), TrUserData);
        get_request -> encode_msg_get_request(id(Msg, TrUserData), TrUserData);
        get_response -> encode_msg_get_response(id(Msg, TrUserData), TrUserData);
        delete_request -> encode_msg_delete_request(id(Msg, TrUserData), TrUserData);
        delete_response -> encode_msg_delete_response(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_key(Msg, TrUserData) -> encode_msg_key(Msg, <<>>, TrUserData).


encode_msg_key(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{channel := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{identifier := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     case is_empty_string(TrF2) of
                         true -> B1;
                         false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    case M of
        #{msg_uuid := F3} ->
            begin
                TrF3 = id(F3, TrUserData),
                case is_empty_string(TrF3) of
                    true -> B2;
                    false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
                end
            end;
        _ -> B2
    end.

encode_msg_value(Msg, TrUserData) -> encode_msg_value(Msg, <<>>, TrUserData).


encode_msg_value(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{json_payload := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{stored_at := F2} -> begin TrF2 = id(F2, TrUserData), e_type_int64(TrF2, <<B1/binary, 16>>, TrUserData) end;
        _ -> B1
    end.

encode_msg_put_request(Msg, TrUserData) -> encode_msg_put_request(Msg, <<>>, TrUserData).


encode_msg_put_request(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{key := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= undefined -> Bin;
                        true -> e_mfield_put_request_key(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{value := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= undefined -> B1;
                        true -> e_mfield_put_request_value(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    case M of
        #{if_absent := F3} ->
            begin
                TrF3 = id(F3, TrUserData),
                if TrF3 =:= false -> B2;
                   true -> e_type_bool(TrF3, <<B2/binary, 24>>, TrUserData)
                end
            end;
        _ -> B2
    end.

encode_msg_put_response(Msg, TrUserData) -> encode_msg_put_response(Msg, <<>>, TrUserData).


encode_msg_put_response(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{created := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= false -> Bin;
                        true -> e_type_bool(TrF1, <<Bin/binary, 8>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{value := F2} ->
            begin
                TrF2 = id(F2, TrUserData),
                if TrF2 =:= undefined -> B1;
                   true -> e_mfield_put_response_value(TrF2, <<B1/binary, 18>>, TrUserData)
                end
            end;
        _ -> B1
    end.

encode_msg_get_request(Msg, TrUserData) -> encode_msg_get_request(Msg, <<>>, TrUserData).


encode_msg_get_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{key := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= undefined -> Bin;
                   true -> e_mfield_get_request_key(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_get_response(Msg, TrUserData) -> encode_msg_get_response(Msg, <<>>, TrUserData).


encode_msg_get_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{value := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= undefined -> Bin;
                   true -> e_mfield_get_response_value(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_delete_request(Msg, TrUserData) -> encode_msg_delete_request(Msg, <<>>, TrUserData).


encode_msg_delete_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{key := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= undefined -> Bin;
                   true -> e_mfield_delete_request_key(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_delete_response(Msg, TrUserData) -> encode_msg_delete_response(Msg, <<>>, TrUserData).


encode_msg_delete_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{deleted := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= false -> Bin;
                   true -> e_type_bool(TrF1, <<Bin/binary, 8>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

e_mfield_put_request_key(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_key(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_put_request_value(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_value(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_put_response_value(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_value(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_get_request_key(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_key(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_get_response_value(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_value(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_delete_request_key(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_key(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(key, Bin, TrUserData) -> id(decode_msg_key(Bin, TrUserData), TrUserData);
decode_msg_2_doit(value, Bin, TrUserData) -> id(decode_msg_value(Bin, TrUserData), TrUserData);
decode_msg_2_doit(put_request, Bin, TrUserData) -> id(decode_msg_put_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(put_response, Bin, TrUserData) -> id(decode_msg_put_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(get_request, Bin, TrUserData) -> id(decode_msg_get_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(get_response, Bin, TrUserData) -> id(decode_msg_get_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(delete_request, Bin, TrUserData) -> id(decode_msg_delete_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(delete_response, Bin, TrUserData) -> id(decode_msg_delete_response(Bin, TrUserData), TrUserData).



decode_msg_key(Bin, TrUserData) -> dfp_read_field_def_key(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_key(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_key_channel(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_key(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_key_identifier(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_key(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_key_msg_uuid(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_key(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{channel => F@_1, identifier => F@_2, msg_uuid => F@_3};
dfp_read_field_def_key(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_key(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_key(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_key(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_key(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_key_channel(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        18 -> d_field_key_identifier(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        26 -> d_field_key_msg_uuid(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_key(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> skip_64_key(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> skip_length_delimited_key(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> skip_group_key(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> skip_32_key(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
dg_read_field_def_key(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{channel => F@_1, identifier => F@_2, msg_uuid => F@_3}.

d_field_key_channel(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_key_channel(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_key_channel(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_key(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_key_identifier(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_key_identifier(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_key_identifier(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_key(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

d_field_key_msg_uuid(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_key_msg_uuid(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_key_msg_uuid(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_key(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_key(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_key(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_key(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_key(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_key(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_key(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_key(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_key(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_key(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_key(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_key(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_key(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_key(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_key(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_value(Bin, TrUserData) -> dfp_read_field_def_value(Bin, 0, 0, 0, id(<<>>, TrUserData), id('$undef', TrUserData), TrUserData).

dfp_read_field_def_value(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_value_json_payload(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_value(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_value_stored_at(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_value(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{json_payload => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{stored_at => F@_2}
    end;
dfp_read_field_def_value(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_value(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_value(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_value(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_value(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_value_json_payload(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        16 -> d_field_value_stored_at(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_value(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_value(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_value(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_value(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_value(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_value(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{json_payload => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{stored_at => F@_2}
    end.

d_field_value_json_payload(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_value_json_payload(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_value_json_payload(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_value(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_value_stored_at(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_value_stored_at(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_value_stored_at(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_value(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_value(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_value(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_value(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_value(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_value(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_value(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_value(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_value(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_value(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_value(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_value(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_value(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_value(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_value(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_put_request(Bin, TrUserData) -> dfp_read_field_def_put_request(Bin, 0, 0, 0, id('$undef', TrUserData), id('$undef', TrUserData), id(false, TrUserData), TrUserData).

dfp_read_field_def_put_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_put_request_key(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_put_request(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_put_request_value(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_put_request(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_put_request_if_absent(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_put_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) ->
    S1 = #{if_absent => F@_3},
    S2 = if F@_1 == '$undef' -> S1;
            true -> S1#{key => F@_1}
         end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{value => F@_2}
    end;
dfp_read_field_def_put_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_put_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_put_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_put_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_put_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_put_request_key(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        18 -> d_field_put_request_value(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        24 -> d_field_put_request_if_absent(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_put_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> skip_64_put_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> skip_length_delimited_put_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> skip_group_put_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> skip_32_put_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
dg_read_field_def_put_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) ->
    S1 = #{if_absent => F@_3},
    S2 = if F@_1 == '$undef' -> S1;
            true -> S1#{key => F@_1}
         end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{value => F@_2}
    end.

d_field_put_request_key(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_put_request_key(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_put_request_key(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_key(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_put_request(RestF,
                                   0,
                                   0,
                                   F,
                                   if Prev == '$undef' -> NewFValue;
                                      true -> merge_msg_key(Prev, NewFValue, TrUserData)
                                   end,
                                   F@_2,
                                   F@_3,
                                   TrUserData).

d_field_put_request_value(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_put_request_value(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_put_request_value(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_value(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_put_request(RestF,
                                   0,
                                   0,
                                   F,
                                   F@_1,
                                   if Prev == '$undef' -> NewFValue;
                                      true -> merge_msg_value(Prev, NewFValue, TrUserData)
                                   end,
                                   F@_3,
                                   TrUserData).

d_field_put_request_if_absent(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_put_request_if_absent(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_put_request_if_absent(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = {id(X bsl N + Acc =/= 0, TrUserData), Rest},
    dfp_read_field_def_put_request(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_put_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_put_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_put_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_put_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_put_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_put_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_put_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_put_request(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_put_request(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_put_request(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_put_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_put_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_put_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_put_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_put_response(Bin, TrUserData) -> dfp_read_field_def_put_response(Bin, 0, 0, 0, id(false, TrUserData), id('$undef', TrUserData), TrUserData).

dfp_read_field_def_put_response(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_put_response_created(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_put_response(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_put_response_value(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_put_response(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{created => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{value => F@_2}
    end;
dfp_read_field_def_put_response(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_put_response(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_put_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_put_response(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_put_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_put_response_created(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_put_response_value(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_put_response(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_put_response(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_put_response(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_put_response(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_put_response(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_put_response(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{created => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{value => F@_2}
    end.

d_field_put_response_created(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_put_response_created(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_put_response_created(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {id(X bsl N + Acc =/= 0, TrUserData), Rest},
    dfp_read_field_def_put_response(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_put_response_value(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_put_response_value(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_put_response_value(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_value(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_put_response(RestF,
                                    0,
                                    0,
                                    F,
                                    F@_1,
                                    if Prev == '$undef' -> NewFValue;
                                       true -> merge_msg_value(Prev, NewFValue, TrUserData)
                                    end,
                                    TrUserData).

skip_varint_put_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_put_response(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_put_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_put_response(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_put_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_put_response(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_put_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_put_response(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_put_response(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_put_response(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_put_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_put_response(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_put_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_put_response(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_get_request(Bin, TrUserData) -> dfp_read_field_def_get_request(Bin, 0, 0, 0, id('$undef', TrUserData), TrUserData).

dfp_read_field_def_get_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_get_request_key(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_get_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{key => F@_1}
    end;
dfp_read_field_def_get_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_get_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_get_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_get_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_get_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_get_request_key(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_get_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_get_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_get_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_get_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_get_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_get_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{key => F@_1}
    end.

d_field_get_request_key(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_get_request_key(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_get_request_key(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_key(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_get_request(RestF,
                                   0,
                                   0,
                                   F,
                                   if Prev == '$undef' -> NewFValue;
                                      true -> merge_msg_key(Prev, NewFValue, TrUserData)
                                   end,
                                   TrUserData).

skip_varint_get_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_get_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_get_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_get_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_get_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_get_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_get_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_get_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_get_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_get_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_get_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_get_response(Bin, TrUserData) -> dfp_read_field_def_get_response(Bin, 0, 0, 0, id('$undef', TrUserData), TrUserData).

dfp_read_field_def_get_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_get_response_value(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_get_response(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{value => F@_1}
    end;
dfp_read_field_def_get_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_get_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_get_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_get_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_get_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_get_response_value(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_get_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_get_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_get_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_get_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_get_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_get_response(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{value => F@_1}
    end.

d_field_get_response_value(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_get_response_value(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_get_response_value(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_value(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_get_response(RestF,
                                    0,
                                    0,
                                    F,
                                    if Prev == '$undef' -> NewFValue;
                                       true -> merge_msg_value(Prev, NewFValue, TrUserData)
                                    end,
                                    TrUserData).

skip_varint_get_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_get_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_get_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_get_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_get_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_get_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_get_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_get_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_get_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_get_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_get_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_delete_request(Bin, TrUserData) -> dfp_read_field_def_delete_request(Bin, 0, 0, 0, id('$undef', TrUserData), TrUserData).

dfp_read_field_def_delete_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_delete_request_key(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_delete_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{key => F@_1}
    end;
dfp_read_field_def_delete_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_delete_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_delete_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_delete_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_delete_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_delete_request_key(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_delete_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_delete_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_delete_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_delete_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_delete_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_delete_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{key => F@_1}
    end.

d_field_delete_request_key(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_delete_request_key(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_delete_request_key(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_key(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_delete_request(RestF,
                                      0,
                                      0,
                                      F,
                                      if Prev == '$undef' -> NewFValue;
                                         true -> merge_msg_key(Prev, NewFValue, TrUserData)
                                      end,
                                      TrUserData).

skip_varint_delete_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_delete_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_delete_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_delete_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_delete_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_delete_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_delete_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_delete_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_delete_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_delete_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_delete_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_delete_response(Bin, TrUserData) -> dfp_read_field_def_delete_response(Bin, 0, 0, 0, id(false, TrUserData), TrUserData).

dfp_read_field_def_delete_response(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_delete_response_deleted(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_delete_response(<<>>, 0, 0, _, F@_1, _) -> #{deleted => F@_1};
dfp_read_field_def_delete_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_delete_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_delete_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_delete_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_delete_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_delete_response_deleted(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_delete_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_delete_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_delete_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_delete_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_delete_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_delete_response(<<>>, 0, 0, _, F@_1, _) -> #{deleted => F@_1}.

d_field_delete_response_deleted(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_delete_response_deleted(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_delete_response_deleted(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {id(X bsl N + Acc =/= 0, TrUserData), Rest},
    dfp_read_field_def_delete_response(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_delete_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_delete_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_delete_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_delete_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_delete_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_delete_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_delete_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_delete_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_delete_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_delete_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_delete_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_delete_response(Rest, Z1, Z2, F, F@_1, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        key -> merge_msg_key(Prev, New, TrUserData);
        value -> merge_msg_value(Prev, New, TrUserData);
        put_request -> merge_msg_put_request(Prev, New, TrUserData);
        put_response -> merge_msg_put_response(Prev, New, TrUserData);
        get_request -> merge_msg_get_request(Prev, New, TrUserData);
        get_response -> merge_msg_get_response(Prev, New, TrUserData);
        delete_request -> merge_msg_delete_request(Prev, New, TrUserData);
        delete_response -> merge_msg_delete_response(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_key/3}).
merge_msg_key(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{channel := NFchannel}} -> S1#{channel => NFchannel};
             {#{channel := PFchannel}, _} -> S1#{channel => PFchannel};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{identifier := NFidentifier}} -> S2#{identifier => NFidentifier};
             {#{identifier := PFidentifier}, _} -> S2#{identifier => PFidentifier};
             _ -> S2
         end,
    case {PMsg, NMsg} of
        {_, #{msg_uuid := NFmsg_uuid}} -> S3#{msg_uuid => NFmsg_uuid};
        {#{msg_uuid := PFmsg_uuid}, _} -> S3#{msg_uuid => PFmsg_uuid};
        _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_value/3}).
merge_msg_value(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{json_payload := NFjson_payload}} -> S1#{json_payload => NFjson_payload};
             {#{json_payload := PFjson_payload}, _} -> S1#{json_payload => PFjson_payload};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {_, #{stored_at := NFstored_at}} -> S2#{stored_at => NFstored_at};
        {#{stored_at := PFstored_at}, _} -> S2#{stored_at => PFstored_at};
        _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_put_request/3}).
merge_msg_put_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {#{key := PFkey}, #{key := NFkey}} -> S1#{key => merge_msg_key(PFkey, NFkey, TrUserData)};
             {_, #{key := NFkey}} -> S1#{key => NFkey};
             {#{key := PFkey}, _} -> S1#{key => PFkey};
             {_, _} -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {#{value := PFvalue}, #{value := NFvalue}} -> S2#{value => merge_msg_value(PFvalue, NFvalue, TrUserData)};
             {_, #{value := NFvalue}} -> S2#{value => NFvalue};
             {#{value := PFvalue}, _} -> S2#{value => PFvalue};
             {_, _} -> S2
         end,
    case {PMsg, NMsg} of
        {_, #{if_absent := NFif_absent}} -> S3#{if_absent => NFif_absent};
        {#{if_absent := PFif_absent}, _} -> S3#{if_absent => PFif_absent};
        _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_put_response/3}).
merge_msg_put_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{created := NFcreated}} -> S1#{created => NFcreated};
             {#{created := PFcreated}, _} -> S1#{created => PFcreated};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {#{value := PFvalue}, #{value := NFvalue}} -> S2#{value => merge_msg_value(PFvalue, NFvalue, TrUserData)};
        {_, #{value := NFvalue}} -> S2#{value => NFvalue};
        {#{value := PFvalue}, _} -> S2#{value => PFvalue};
        {_, _} -> S2
    end.

-compile({nowarn_unused_function,merge_msg_get_request/3}).
merge_msg_get_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{key := PFkey}, #{key := NFkey}} -> S1#{key => merge_msg_key(PFkey, NFkey, TrUserData)};
        {_, #{key := NFkey}} -> S1#{key => NFkey};
        {#{key := PFkey}, _} -> S1#{key => PFkey};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_get_response/3}).
merge_msg_get_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{value := PFvalue}, #{value := NFvalue}} -> S1#{value => merge_msg_value(PFvalue, NFvalue, TrUserData)};
        {_, #{value := NFvalue}} -> S1#{value => NFvalue};
        {#{value := PFvalue}, _} -> S1#{value => PFvalue};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_delete_request/3}).
merge_msg_delete_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{key := PFkey}, #{key := NFkey}} -> S1#{key => merge_msg_key(PFkey, NFkey, TrUserData)};
        {_, #{key := NFkey}} -> S1#{key => NFkey};
        {#{key := PFkey}, _} -> S1#{key => PFkey};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_delete_response/3}).
merge_msg_delete_response(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{deleted := NFdeleted}} -> S1#{deleted => NFdeleted};
        {#{deleted := PFdeleted}, _} -> S1#{deleted => PFdeleted};
        _ -> S1
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        key -> v_msg_key(Msg, [MsgName], TrUserData);
        value -> v_msg_value(Msg, [MsgName], TrUserData);
        put_request -> v_msg_put_request(Msg, [MsgName], TrUserData);
        put_response -> v_msg_put_response(Msg, [MsgName], TrUserData);
        get_request -> v_msg_get_request(Msg, [MsgName], TrUserData);
        get_response -> v_msg_get_response(Msg, [MsgName], TrUserData);
        delete_request -> v_msg_delete_request(Msg, [MsgName], TrUserData);
        delete_response -> v_msg_delete_response(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_submsg_key/3}).
-dialyzer({nowarn_function,v_submsg_key/3}).
v_submsg_key(Msg, Path, TrUserData) -> v_msg_key(Msg, Path, TrUserData).

-compile({nowarn_unused_function,v_msg_key/3}).
-dialyzer({nowarn_function,v_msg_key/3}).
v_msg_key(#{} = M, Path, TrUserData) ->
    case M of
        #{channel := F1} -> v_type_string(F1, [channel | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{identifier := F2} -> v_type_string(F2, [identifier | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{msg_uuid := F3} -> v_type_string(F3, [msg_uuid | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (channel) -> ok;
                      (identifier) -> ok;
                      (msg_uuid) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_key(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), key}, M, Path);
v_msg_key(X, Path, _TrUserData) -> mk_type_error({expected_msg, key}, X, Path).

-compile({nowarn_unused_function,v_submsg_value/3}).
-dialyzer({nowarn_function,v_submsg_value/3}).
v_submsg_value(Msg, Path, TrUserData) -> v_msg_value(Msg, Path, TrUserData).

-compile({nowarn_unused_function,v_msg_value/3}).
-dialyzer({nowarn_function,v_msg_value/3}).
v_msg_value(#{} = M, Path, TrUserData) ->
    case M of
        #{json_payload := F1} -> v_type_string(F1, [json_payload | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{stored_at := F2} -> v_type_int64(F2, [stored_at | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (json_payload) -> ok;
                      (stored_at) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_value(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), value}, M, Path);
v_msg_value(X, Path, _TrUserData) -> mk_type_error({expected_msg, value}, X, Path).

-compile({nowarn_unused_function,v_msg_put_request/3}).
-dialyzer({nowarn_function,v_msg_put_request/3}).
v_msg_put_request(#{} = M, Path, TrUserData) ->
    case M of
        #{key := F1} -> v_submsg_key(F1, [key | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{value := F2} -> v_submsg_value(F2, [value | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{if_absent := F3} -> v_type_bool(F3, [if_absent | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (key) -> ok;
                      (value) -> ok;
                      (if_absent) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_put_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), put_request}, M, Path);
v_msg_put_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, put_request}, X, Path).

-compile({nowarn_unused_function,v_msg_put_response/3}).
-dialyzer({nowarn_function,v_msg_put_response/3}).
v_msg_put_response(#{} = M, Path, TrUserData) ->
    case M of
        #{created := F1} -> v_type_bool(F1, [created | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{value := F2} -> v_submsg_value(F2, [value | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (created) -> ok;
                      (value) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_put_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), put_response}, M, Path);
v_msg_put_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, put_response}, X, Path).

-compile({nowarn_unused_function,v_msg_get_request/3}).
-dialyzer({nowarn_function,v_msg_get_request/3}).
v_msg_get_request(#{} = M, Path, TrUserData) ->
    case M of
        #{key := F1} -> v_submsg_key(F1, [key | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (key) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_get_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), get_request}, M, Path);
v_msg_get_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, get_request}, X, Path).

-compile({nowarn_unused_function,v_msg_get_response/3}).
-dialyzer({nowarn_function,v_msg_get_response/3}).
v_msg_get_response(#{} = M, Path, TrUserData) ->
    case M of
        #{value := F1} -> v_submsg_value(F1, [value | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (value) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_get_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), get_response}, M, Path);
v_msg_get_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, get_response}, X, Path).

-compile({nowarn_unused_function,v_msg_delete_request/3}).
-dialyzer({nowarn_function,v_msg_delete_request/3}).
v_msg_delete_request(#{} = M, Path, TrUserData) ->
    case M of
        #{key := F1} -> v_submsg_key(F1, [key | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (key) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_delete_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), delete_request}, M, Path);
v_msg_delete_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, delete_request}, X, Path).

-compile({nowarn_unused_function,v_msg_delete_response/3}).
-dialyzer({nowarn_function,v_msg_delete_response/3}).
v_msg_delete_response(#{} = M, Path, TrUserData) ->
    case M of
        #{deleted := F1} -> v_type_bool(F1, [deleted | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (deleted) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_delete_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), delete_response}, M, Path);
v_msg_delete_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, delete_response}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when is_integer(N), -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_bool/3}).
-dialyzer({nowarn_function,v_type_bool/3}).
v_type_bool(false, _Path, _TrUserData) -> ok;
v_type_bool(true, _Path, _TrUserData) -> ok;
v_type_bool(0, _Path, _TrUserData) -> ok;
v_type_bool(1, _Path, _TrUserData) -> ok;
v_type_bool(X, Path, _TrUserData) -> mk_type_error(bad_boolean_value, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, key},
      [#{name => channel, fnum => 1, rnum => 2, type => string, occurrence => defaulty, opts => []},
       #{name => identifier, fnum => 2, rnum => 3, type => string, occurrence => defaulty, opts => []},
       #{name => msg_uuid, fnum => 3, rnum => 4, type => string, occurrence => defaulty, opts => []}]},
     {{msg, value}, [#{name => json_payload, fnum => 1, rnum => 2, type => string, occurrence => defaulty, opts => []}, #{name => stored_at, fnum => 2, rnum => 3, type => int64, occurrence => optional, opts => []}]},
     {{msg, put_request},
      [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []},
       #{name => value, fnum => 2, rnum => 3, type => {msg, value}, occurrence => defaulty, opts => []},
       #{name => if_absent, fnum => 3, rnum => 4, type => bool, occurrence => defaulty, opts => []}]},
     {{msg, put_response}, [#{name => created, fnum => 1, rnum => 2, type => bool, occurrence => defaulty, opts => []}, #{name => value, fnum => 2, rnum => 3, type => {msg, value}, occurrence => defaulty, opts => []}]},
     {{msg, get_request}, [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []}]},
     {{msg, get_response}, [#{name => value, fnum => 1, rnum => 2, type => {msg, value}, occurrence => defaulty, opts => []}]},
     {{msg, delete_request}, [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []}]},
     {{msg, delete_response}, [#{name => deleted, fnum => 1, rnum => 2, type => bool, occurrence => defaulty, opts => []}]}].


get_msg_names() -> [key, value, put_request, put_response, get_request, get_response, delete_request, delete_response].


get_group_names() -> [].


get_msg_or_group_names() -> [key, value, put_request, put_response, get_request, get_response, delete_request, delete_response].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def(key) ->
    [#{name => channel, fnum => 1, rnum => 2, type => string, occurrence => defaulty, opts => []},
     #{name => identifier, fnum => 2, rnum => 3, type => string, occurrence => defaulty, opts => []},
     #{name => msg_uuid, fnum => 3, rnum => 4, type => string, occurrence => defaulty, opts => []}];
find_msg_def(value) -> [#{name => json_payload, fnum => 1, rnum => 2, type => string, occurrence => defaulty, opts => []}, #{name => stored_at, fnum => 2, rnum => 3, type => int64, occurrence => optional, opts => []}];
find_msg_def(put_request) ->
    [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []},
     #{name => value, fnum => 2, rnum => 3, type => {msg, value}, occurrence => defaulty, opts => []},
     #{name => if_absent, fnum => 3, rnum => 4, type => bool, occurrence => defaulty, opts => []}];
find_msg_def(put_response) -> [#{name => created, fnum => 1, rnum => 2, type => bool, occurrence => defaulty, opts => []}, #{name => value, fnum => 2, rnum => 3, type => {msg, value}, occurrence => defaulty, opts => []}];
find_msg_def(get_request) -> [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []}];
find_msg_def(get_response) -> [#{name => value, fnum => 1, rnum => 2, type => {msg, value}, occurrence => defaulty, opts => []}];
find_msg_def(delete_request) -> [#{name => key, fnum => 1, rnum => 2, type => {msg, key}, occurrence => defaulty, opts => []}];
find_msg_def(delete_response) -> [#{name => deleted, fnum => 1, rnum => 2, type => bool, occurrence => defaulty, opts => []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> ['rocksbdhandler.MessageStateStore'].


get_service_def('rocksbdhandler.MessageStateStore') ->
    {{service, 'rocksbdhandler.MessageStateStore'},
     [#{name => 'Put', input => put_request, output => put_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'Get', input => get_request, output => get_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'Delete', input => delete_request, output => delete_response, input_stream => false, output_stream => false, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('rocksbdhandler.MessageStateStore') -> ['Put', 'Get', 'Delete'];
get_rpc_names(_) -> error.


find_rpc_def('rocksbdhandler.MessageStateStore', RpcName) -> 'find_rpc_def_rocksbdhandler.MessageStateStore'(RpcName);
find_rpc_def(_, _) -> error.


'find_rpc_def_rocksbdhandler.MessageStateStore'('Put') -> #{name => 'Put', input => put_request, output => put_response, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_rocksbdhandler.MessageStateStore'('Get') -> #{name => 'Get', input => get_request, output => get_response, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_rocksbdhandler.MessageStateStore'('Delete') -> #{name => 'Delete', input => delete_request, output => delete_response, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_rocksbdhandler.MessageStateStore'(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_map(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"rocksbdhandler.MessageStateStore">>) -> 'rocksbdhandler.MessageStateStore';
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin('rocksbdhandler.MessageStateStore') -> <<"rocksbdhandler.MessageStateStore">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"rocksbdhandler.MessageStateStore">>, <<"Put">>) -> {'rocksbdhandler.MessageStateStore', 'Put'};
fqbins_to_service_and_rpc_name(<<"rocksbdhandler.MessageStateStore">>, <<"Get">>) -> {'rocksbdhandler.MessageStateStore', 'Get'};
fqbins_to_service_and_rpc_name(<<"rocksbdhandler.MessageStateStore">>, <<"Delete">>) -> {'rocksbdhandler.MessageStateStore', 'Delete'};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins('rocksbdhandler.MessageStateStore', 'Put') -> {<<"rocksbdhandler.MessageStateStore">>, <<"Put">>};
service_and_rpc_name_to_fqbins('rocksbdhandler.MessageStateStore', 'Get') -> {<<"rocksbdhandler.MessageStateStore">>, <<"Get">>};
service_and_rpc_name_to_fqbins('rocksbdhandler.MessageStateStore', 'Delete') -> {<<"rocksbdhandler.MessageStateStore">>, <<"Delete">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"rocksbdhandler.Key">>) -> key;
fqbin_to_msg_name(<<"rocksbdhandler.Value">>) -> value;
fqbin_to_msg_name(<<"rocksbdhandler.PutRequest">>) -> put_request;
fqbin_to_msg_name(<<"rocksbdhandler.PutResponse">>) -> put_response;
fqbin_to_msg_name(<<"rocksbdhandler.GetRequest">>) -> get_request;
fqbin_to_msg_name(<<"rocksbdhandler.GetResponse">>) -> get_response;
fqbin_to_msg_name(<<"rocksbdhandler.DeleteRequest">>) -> delete_request;
fqbin_to_msg_name(<<"rocksbdhandler.DeleteResponse">>) -> delete_response;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(key) -> <<"rocksbdhandler.Key">>;
msg_name_to_fqbin(value) -> <<"rocksbdhandler.Value">>;
msg_name_to_fqbin(put_request) -> <<"rocksbdhandler.PutRequest">>;
msg_name_to_fqbin(put_response) -> <<"rocksbdhandler.PutResponse">>;
msg_name_to_fqbin(get_request) -> <<"rocksbdhandler.GetRequest">>;
msg_name_to_fqbin(get_response) -> <<"rocksbdhandler.GetResponse">>;
msg_name_to_fqbin(delete_request) -> <<"rocksbdhandler.DeleteRequest">>;
msg_name_to_fqbin(delete_response) -> <<"rocksbdhandler.DeleteResponse">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> rocksbdhandler.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "route_guide.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["route_guide.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["route_guide"].


get_msg_containment("route_guide") -> [delete_request, delete_response, get_request, get_response, key, put_request, put_response, value];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("route_guide") -> rocksbdhandler;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("route_guide") -> ['rocksbdhandler.MessageStateStore'];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("route_guide") -> [{'rocksbdhandler.MessageStateStore', 'Put'}, {'rocksbdhandler.MessageStateStore', 'Get'}, {'rocksbdhandler.MessageStateStore', 'Delete'}];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("route_guide") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.PutRequest">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.GetRequest">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.DeleteRequest">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.Value">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.PutResponse">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.GetResponse">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.DeleteResponse">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(<<"rocksbdhandler.Key">>) -> "route_guide";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"rocksbdhandler.MessageStateStore">>) -> "route_guide";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"rocksbdhandler">>) -> ["route_guide"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.21.5".

gpb_version_as_list() ->
    [4,21,5].

gpb_version_source() ->
    "file".
